version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.1"
ports: "80:80"

packages: [php8.1-curl, php8.1-http, php8.1-raphf, php8.1-redis, php8.1-sqlite]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"
    - "sudo chmod -R 777 /opt/mock/repos"

  run:
    - "sudo -E mkdir -p /data"
    - "sudo -E chmod -R 777 /data"

  dev:
  test:


